# WebSocket message types
WS_ERROR_MESSAGE = 1
WS_EXCEPTION_MESSAGE = 305
WS_NOTIFICATION_MESSAGE = 10
WS_TYPE_PING = 116
WS_TYPE_MARK_READ = 1001
WS_TYPE_CHAT_MESSAGE = 1000
WS_TYPE_ERROR = 113
WS_CHAT_SCREEN_OPEN = 100  # open chat
WS_CHAT_SCREEN_CLOSE = 103  # close chat
WS_ACTION_START = 304
WS_ACTION_END = 306


NOTIFICATION_TYPE_NEW_MESSAGE = 18
NOTIFICATION_TYPE_VOICEC_INVITE = 29
NOTIFICATION_TYPE_VIDEOC_INVITE = 37


ACTION_TYPING = "Typing"
ACTION_RECORDING = "Recording"
ACTION_CHATTING = "Chatting"  # start - turn on screen, end turn off screen
ACTION_BROWSING = "Browsing"


TTL_TYPING = 30
TTL_RECORDING = 30
TTL_VIEWER = 40
TTL_CHATTING = 120
TTL_COMMUNITY_ONLINE = 300
